export default {
    ON_LOGIN_SUCCESS: "ON_LOGIN_SUCCESS",
    ON_LOGIN_FAIL: "ON_LOGIN_FAIL",
    ON_LOGOUT_SUCCESS: "ON_LOGOUT_SUCCESS",
    ON_SEARCH: "ON_SEARCH",
    ON_ADD_QUANTITY_CART: "ON_ADD_QUANTITY_CART"
};
